import type { Metadata, Viewport } from "next";
import { Inter } from "next/font/google";
import "./globals.css";

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
  generator: "Next.js",
  manifest: "/manifest.json",
  icons: [
    { rel: "icon", url: "icons/logo144.png" },
    { rel: "apple-touch-icon", url: "icons/logo144.png" },
  ],
};

export const viewport: Viewport = {
  themeColor: [{media: "(prefers-color-scheme: light)", color: "#fff"}, {media: "(prefers-color-scheme: dark)", color: "#000"}],
  width: "device-width",
  initialScale: 1,
  minimumScale: 1,
  viewportFit: "cover",
}

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={inter.className}>{children}</body>
    </html>
  );
}
